<cfscript>
function ttBase(required string title){
    var sub=request.ttSub?:"/";var nav='<nav class="workspace-subnav" aria-label="Training Tracker"><a '&((sub=="/"||left(sub,6)=="/week/"||left(sub,9)=="/session/"||left(sub,7)=="/topic/"||left(sub,7)=="/video/")?'class="active" ':'')&'href="/training-tracker/">Weeks</a><a '&(sub=="/people"||left(sub,8)=="/people/"?'class="active" ':'')&'href="/training-tracker/people">Roster</a><a '&(left(sub,8)=="/reports"?'class="active" ':'')&'href="/training-tracker/reports">Reports</a><a '&(sub=="/account"?'class="active" ':'')&'href="/training-tracker/account">Account</a>';
    if(request.ttIsAdmin)nav&='<a '&(left(sub,6)=="/admin"?'class="active" ':'')&'href="/training-tracker/admin">Edit Content</a>';
    return workspaceShellStart(request.ttUser,"training-tracker",arguments.title,nav&'</nav>');
}
function ttEnd(){return workspaceShellEnd();}
function ttBackWeek(required numeric id){return '/training-tracker/week/'&arguments.id;}
function ttRequireEdit(){if(!request.ttCanEdit)htmlOut(ttBase("Access denied")&'<p>You do not have permission to edit Training Tracker.</p>'&ttEnd(),403);}
function ttRequireAdmin(){if(!request.ttIsAdmin)htmlOut(ttBase("Access denied")&'<p>Training Tracker administrator access is required.</p>'&ttEnd(),403);}
function ttSessionIdFrom(required struct match,required numeric index){return val(mid(request.ttSub,match.pos[index],match.len[index]));}
function ttContentFields(required struct values){var keys=structKeyArray(values);arraySort(keys,"textnocase");var h='';for(var k in keys)h&='<label style="display:block;margin:8px 0"><span class="muted">'&encodeForHtml(k)&'</span><br><input name="'&encodeForHtmlAttribute(k)&'" value="'&encodeForHtmlAttribute(values[k])&'" style="width:min(760px,100%)"></label>';return h;}

request.ttUser=requireLogin();request.ttRole=application.auth.getRole(request.ttUser,"training-tracker");if(!len(request.ttRole))redirectTo("/");request.ttCanEdit=listFindNoCase("admin,editor",request.ttRole)>0;request.ttIsAdmin=request.ttRole=="admin";request.ttSub=removeChars(path,1,len("/training-tracker"));if(!len(request.ttSub))request.ttSub="/";sub=request.ttSub;

// Dashboard / weeks
if(sub=="/"&&method=="GET"){
    c=application.training.content();weeks=application.training.weeks();h=ttBase(c["site.name"]?:"Training Ledger")&'<p class="muted">'&encodeForHtml(c["site.tagline"]?:"weekly curriculum")&'</p><h2>'&encodeForHtml(c["index.heading"]?:"The Curriculum, Week by Week")&'</h2>';
    if(request.ttCanEdit)h&='<div class="card"><form method="post" action="/training-tracker/week/new"><input name="title" placeholder="Week title"><input type="date" name="start_date"><button>'&encodeForHtml(c["index.new_week_btn"]?:"+ New Week")&'</button></form></div>';
    if(!arrayLen(weeks))h&='<div class="card"><strong>'&encodeForHtml(c["index.empty_title"]?:"No entries yet")&'</strong><p>'&encodeForHtml(c["index.empty_body"]?:"Start the ledger with your first training week.")&'</p></div>';
    for(w in weeks)h&='<div class="card"><a href="/training-tracker/week/'&w.id&'"><strong>Week '&numberFormat(w.week_number,"00")&': '&encodeForHtml(w.title)&'</strong></a><div class="muted">'&encodeForHtml(w.start_date?:"")&' &middot; '&w.topic_count&' topics &middot; '&w.session_count&' sessions &middot; '&w.signed_count&' / '&w.attended_count&' signed</div></div>';
    htmlOut(h&'<p class="muted">'&encodeForHtml(c["site.footer"]?:"")&'</p>'&ttEnd());
}
if(sub=="/week/new"&&method=="POST"){ttRequireEdit();id=application.training.createWeek(form.title?:"",form.start_date?:"",form.notes?:"");redirectTo(ttBackWeek(id));}
wm=reFind("^/week/([0-9]+)$",sub,1,true);
if(wm.len[1]&&method=="GET"){
    wid=ttSessionIdFrom(wm,2);w=application.training.week(wid);if(!structCount(w))htmlOut(ttBase("Not found")&'<p>Training week not found.</p>'&ttEnd(),404);
    h=ttBase("Week "&numberFormat(w.week_number,"00")&": "&w.title)&'<div class="card"><strong>Start date:</strong> '&encodeForHtml(w.start_date?:"")&'<br><strong>Notes:</strong> '&encodeForHtml(w.notes?:"")&'<br><strong>Progress:</strong> '&w.signed&' signed / '&w.attended&' attended</div>';
    if(request.ttCanEdit)h&='<div class="card"><h2>Edit week</h2><form method="post" action="/training-tracker/week/'&wid&'/edit"><input name="title" value="'&encodeForHtmlAttribute(w.title)&'" required><input type="date" name="start_date" value="'&encodeForHtmlAttribute(w.start_date?:"")&'"><textarea name="notes">'&encodeForHtml(w.notes?:"")&'</textarea><button>Save</button></form><form method="post" action="/training-tracker/week/'&wid&'/delete" style="margin-top:8px"><button class="danger">Delete week</button></form></div>';
    h&='<h2>Topics & Lesson Plans</h2>';for(t in w.topics){h&='<div class="card"><strong>'&encodeForHtml(t.title)&'</strong><p>'&encodeForHtml(t.lesson_plan?:"")&'</p><pre style="white-space:pre-wrap">'&encodeForHtml(t.key_points?:"")&'</pre>';if(arrayLen(t.videos)){h&='<ul>';for(v in t.videos)h&='<li><a href="'&encodeForHtmlAttribute(v.url)&'">'&encodeForHtml(v.title?:v.url)&'</a>'&(request.ttCanEdit?' <form class="inline" method="post" action="/training-tracker/video/'&v.id&'/delete"><button class="danger">Delete</button></form>':'')&'</li>';h&='</ul>';}if(request.ttCanEdit)h&='<form method="post" action="/training-tracker/topic/'&t.id&'/edit"><input name="title" value="'&encodeForHtmlAttribute(t.title)&'"><textarea name="lesson_plan">'&encodeForHtml(t.lesson_plan?:"")&'</textarea><textarea name="key_points">'&encodeForHtml(t.key_points?:"")&'</textarea><button>Save topic</button></form><form class="inline" method="post" action="/training-tracker/topic/'&t.id&'/delete"><button class="danger">Delete topic</button></form><form method="post" action="/training-tracker/topic/'&t.id&'/video/add"><input name="video_title" placeholder="Video label"><input name="url" type="url" placeholder="https://..." required><button>Link</button></form>';h&='</div>';}
    if(request.ttCanEdit)h&='<div class="card"><form method="post" action="/training-tracker/week/'&wid&'/topic/new"><input name="title" placeholder="Topic" required><textarea name="lesson_plan" placeholder="Lesson plan"></textarea><textarea name="key_points" placeholder="Key points, one per line"></textarea><button>+ Add Topic</button></form></div>';
    h&='<h2>Sessions</h2>';for(s in w.sessions){h&='<div class="card"><a href="/training-tracker/session/'&s.id&'"><strong>'&encodeForHtml(s.trainer_name)&'</strong></a> &middot; '&encodeForHtml(s.session_date?:"")&' &middot; '&encodeForHtml(s.location?:"")&'<br><span class="muted">'&s.attended_count&' attended &middot; '&s.signed_count&' signed</span>';if(structCount(s.upload?:{}))h&='<br><a href="/training-tracker/session/'&s.id&'/signoff/view">View uploaded signed sheet</a>';if(request.ttCanEdit)h&='<form method="post" action="/training-tracker/session/'&s.id&'/edit"><input name="trainer_name" value="'&encodeForHtmlAttribute(s.trainer_name)&'"><input type="date" name="session_date" value="'&encodeForHtmlAttribute(s.session_date?:"")&'"><input name="location" value="'&encodeForHtmlAttribute(s.location?:"")&'"><button>Save</button></form><form class="inline" method="post" action="/training-tracker/session/'&s.id&'/delete"><button class="danger">Delete</button></form>';h&='</div>';}
    if(request.ttCanEdit)h&='<div class="card"><form method="post" action="/training-tracker/week/'&wid&'/session/new"><input name="trainer_name" placeholder="Trainer"><input type="date" name="session_date"><input name="location" placeholder="Location"><button>+ New Session</button></form></div>';
    htmlOut(h&ttEnd());
}
we=reFind("^/week/([0-9]+)/(edit|delete)$",sub,1,true);if(we.len[1]&&method=="POST"){ttRequireEdit();wid=ttSessionIdFrom(we,2);action=mid(sub,we.pos[3],we.len[3]);if(action=="edit"){application.training.updateWeek(wid,form.title?:"",form.start_date?:"",form.notes?:"");redirectTo(ttBackWeek(wid));}application.training.deleteWeek(wid);redirectTo("/training-tracker/");}

// Sessions
sn=reFind("^/week/([0-9]+)/session/new$",sub,1,true);if(sn.len[1]&&method=="POST"){ttRequireEdit();wid=ttSessionIdFrom(sn,2);application.training.createSession(wid,form.trainer_name?:"",form.session_date?:"",form.location?:"");redirectTo(ttBackWeek(wid));}
se=reFind("^/session/([0-9]+)/(edit|delete)$",sub,1,true);if(se.len[1]&&method=="POST"){ttRequireEdit();sid=ttSessionIdFrom(se,2);sess=application.training.session(sid);if(!structCount(sess))htmlOut("Not found",404);action=mid(sub,se.pos[3],se.len[3]);if(action=="edit")application.training.updateSession(sid,form.trainer_name?:"",form.session_date?:"",form.location?:"");else application.training.deleteSession(sid);redirectTo(ttBackWeek(sess.week_id));}
sg=reFind("^/session/([0-9]+)$",sub,1,true);if(sg.len[1]&&method=="GET"){sid=ttSessionIdFrom(sg,2);sess=application.training.session(sid);if(!structCount(sess))htmlOut(ttBase("Not found")&'<p>Session not found.</p>'&ttEnd(),404);h=ttBase("Sign-off - "&sess.trainer_name)&'<p><a href="'&ttBackWeek(sess.week_id)&'">&larr; Week '&numberFormat(sess.week_number,"00")&'</a></p><div class="card"><strong>'&encodeForHtml(sess.week_title)&'</strong><br>'&encodeForHtml(sess.session_date?:"")&' &middot; '&encodeForHtml(sess.location?:"")&'</div><table><tr><th>Name</th><th>Attended</th><th>Digital signature</th></tr>';for(a in sess.attendance){h&='<tr><td>'&encodeForHtml(a.name)&'</td><td>'&(val(a.attended)?'Yes':'No')&'</td><td>'&encodeForHtml(a.signature?:"")&'</td></tr>';}h&='</table>';if(request.ttCanEdit){h&='<div class="card"><h2>Attendance & digital sign-off</h2>';for(a in sess.attendance)h&='<form method="post" action="/training-tracker/session/'&sid&'/attendance/'&a.person_id&'" style="margin:7px 0"><strong>'&encodeForHtml(a.name)&'</strong> <label><input type="checkbox" name="attended" '&(val(a.attended)?'checked':'')&'> Attended</label> <input name="signature" value="'&encodeForHtmlAttribute(a.signature?:"")&'" placeholder="Signature"><button>Save</button></form>';h&='<p><a class="btn" href="/training-tracker/session/'&sid&'/signoff/download">Download Sign-off Template</a></p><form method="post" enctype="multipart/form-data" action="/training-tracker/session/'&sid&'/signoff/upload"><input type="file" name="signoff_file" accept=".pdf,.png,.jpg,.jpeg,.gif,.webp,.heic" required><button>Upload Signed Sheet</button></form>';if(structCount(sess.upload?:{}))h&='<p><a href="/training-tracker/session/'&sid&'/signoff/view">View uploaded sheet</a></p><form method="post" action="/training-tracker/session/'&sid&'/signoff/remove"><button class="danger">Remove uploaded sheet</button></form>';h&='</div>';}htmlOut(h&ttEnd());}
oldAttendance=reFind("^/session/([0-9]+)/attendance/toggle$",sub,1,true);if(oldAttendance.len[1]&&method=="POST"){ttRequireEdit();sid=ttSessionIdFrom(oldAttendance,2);application.training.toggleAttendance(sid,val(form.person_id?:0),(form.attended?:"")=="1");jsonOut({ok:true});}
newAttendance=reFind("^/session/([0-9]+)/attendance/([0-9]+)$",sub,1,true);if(newAttendance.len[1]&&method=="POST"){ttRequireEdit();sid=ttSessionIdFrom(newAttendance,2);pid=ttSessionIdFrom(newAttendance,3);application.training.setAttendance(sid,pid,structKeyExists(form,"attended"));if(len(trim(form.signature?:"")))application.training.sign(sid,pid,form.signature);redirectTo("/training-tracker/session/"&sid);}

// Topics / videos
tn=reFind("^/week/([0-9]+)/topic/new$",sub,1,true);if(tn.len[1]&&method=="POST"){ttRequireEdit();wid=ttSessionIdFrom(tn,2);application.training.createTopic(wid,form.title?:"",form.lesson_plan?:"",form.key_points?:"");redirectTo(ttBackWeek(wid));}
te=reFind("^/topic/([0-9]+)/(edit|delete)$",sub,1,true);if(te.len[1]&&method=="POST"){ttRequireEdit();tid=ttSessionIdFrom(te,2);topic=application.training.topic(tid);if(!structCount(topic))htmlOut("Not found",404);action=mid(sub,te.pos[3],te.len[3]);if(action=="edit")application.training.updateTopic(tid,form.title?:"",form.lesson_plan?:"",form.key_points?:"");else application.training.deleteTopic(tid);redirectTo(ttBackWeek(topic.week_id));}
va=reFind("^/topic/([0-9]+)/video/add$",sub,1,true);if(va.len[1]&&method=="POST"){ttRequireEdit();tid=ttSessionIdFrom(va,2);topic=application.training.topic(tid);application.training.addVideo(tid,form.video_title?:"",form.url?:"");redirectTo(ttBackWeek(topic.week_id));}
vd=reFind("^/video/([0-9]+)/delete$",sub,1,true);if(vd.len[1]&&method=="POST"){ttRequireEdit();vid=ttSessionIdFrom(vd,2);v=application.training.video(vid);application.training.deleteVideo(vid);redirectTo(ttBackWeek(v.week_id));}

// Roster
if(sub=="/people"&&method=="GET"){h=ttBase("Roster");for(p in application.training.people())h&='<div class="card"><strong>'&encodeForHtml(p.name)&'</strong> &middot; '&encodeForHtml(p.email?:"")&(request.ttCanEdit?' <form class="inline" method="post" action="/training-tracker/people/'&p.id&'/delete"><button class="danger">Delete</button></form>':'')&'</div>';if(request.ttCanEdit)h&='<div class="card"><form method="post" action="/training-tracker/people/add"><input name="name" required placeholder="Name"><input name="email" placeholder="Email"><button>+ Add Person</button></form></div>';htmlOut(h&ttEnd());}
if((sub=="/people/add"||sub=="/people")&&method=="POST"){ttRequireEdit();application.training.addPerson(form.name?:"",form.email?:"");redirectTo("/training-tracker/people");}
pd=reFind("^/people/([0-9]+)/delete$",sub,1,true);if(pd.len[1]&&method=="POST"){ttRequireEdit();application.training.deletePerson(ttSessionIdFrom(pd,2));redirectTo("/training-tracker/people");}

// Sign-off scans and template
sd=reFind("^/session/([0-9]+)/signoff/(download|upload|view|remove)$",sub,1,true);if(sd.len[1]){ttRequireEdit();sid=ttSessionIdFrom(sd,2);action=mid(sub,sd.pos[3],sd.len[3]);sess=application.training.session(sid);if(!structCount(sess))htmlOut("Not found",404);
    if(action=="download"&&method=="GET"){attendees=[];for(a in sess.attendance)if(val(a.attended))arrayAppend(attendees,a);filename="Week "&numberFormat(sess.week_number,"00")&" Sign-off Template"&(sess.trainer_name!="Unassigned"?" - "&reReplace(sess.trainer_name,"[^A-Za-z0-9._ -]","_","all"):"")&".pdf";pdf=application.trainingPdf.build(sess,attendees);cfheader(name="Content-Disposition",value='attachment; filename="'&filename&'"');cfcontent(type="application/pdf",variable=pdf,reset=true);abort;}
    if(action=="upload"&&method=="POST"){f=fileUpload(application.uploadPath,"signoff_file","","makeunique",true,["pdf","png","jpg","jpeg","gif","webp","heic"]);try{application.training.saveSignoff(sid,f.serverDirectory&"/"&f.serverFile,f.clientFile,f.contentType?:"application/octet-stream",request.ttUser.username);}finally{try{fileDelete(f.serverDirectory&"/"&f.serverFile);}catch(any ignored){}}redirectTo(ttBackWeek(sess.week_id));}
    if(action=="view"&&method=="GET"){up=application.training.signoffUpload(sid);real=application.training.signoffPath(sid);if(!len(real))htmlOut("Not found",404);cfheader(name="Content-Disposition",value='inline; filename="'&getFileFromPath(up.original_filename?:up.filename)&'"');cfcontent(file=real,type=up.content_type?:"application/octet-stream",reset=true);abort;}
    if(action=="remove"&&method=="POST"){application.training.removeSignoff(sid);redirectTo(ttBackWeek(sess.week_id));}
}

// Reports
if(sub=="/reports"&&method=="GET"){ttRequireEdit();weeks=application.training.weeks();h=ttBase("Reports")&'<div class="card"><h2>Signed Sign-off Sheets</h2><form method="get" action="/training-tracker/reports/signoff-zip"><input name="start_week" type="number" placeholder="Start week"><input name="end_week" type="number" placeholder="End week"><button>Download ZIP</button></form></div><div class="card"><h2>Attendance Matrix</h2><form method="get" action="/training-tracker/reports/attendance-matrix"><input name="start_week" type="number" placeholder="Start week"><input name="end_week" type="number" placeholder="End week"><button>Download Excel</button></form></div><p>'&arrayLen(weeks)&' training weeks available.</p>';htmlOut(h&ttEnd());}
if(sub=="/reports/signoff-zip"&&method=="GET"){ttRequireEdit();r=application.training.weekRange(url.start_week?:"",url.end_week?:"");if(!r.ok)htmlOut(ttBase("Reports")&'<p>'&encodeForHtml(r.error)&'</p>'&ttEnd(),400);fn=application.training.buildSignoffZip(r.lo,r.hi);if(!len(fn))htmlOut(ttBase("Reports")&'<p>No signed sheets have been uploaded for that range yet.</p>'&ttEnd(),404);cfheader(name="Content-Disposition",value='attachment; filename="'&fn&'"');cfcontent(file=application.outputPath&fn,type="application/zip",reset=true);abort;}
if(sub=="/reports/attendance-matrix"&&method=="GET"){ttRequireEdit();r=application.training.weekRange(url.start_week?:"",url.end_week?:"");if(!r.ok)htmlOut(ttBase("Reports")&'<p>'&encodeForHtml(r.error)&'</p>'&ttEnd(),400);fn=application.training.buildAttendanceMatrix(r.lo,r.hi);cfheader(name="Content-Disposition",value='attachment; filename="'&fn&'"');cfcontent(file=application.outputPath&fn,type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",reset=true);abort;}

// Account and Training Tracker administration
if(sub=="/account"&&method=="GET")htmlOut(ttBase("Account")&'<div class="card"><strong>User:</strong> '&encodeForHtml(request.ttUser.username)&'<br><strong>Training Tracker role:</strong> '&encodeForHtml(request.ttRole)&'</div>'&ttEnd());
if(sub=="/admin"&&method=="GET"){ttRequireAdmin();values=application.training.content();theme=application.training.theme();h=ttBase("Edit Content & Appearance")&'<div class="card"><h2>Content</h2><form method="post" action="/training-tracker/admin/content/save">'&ttContentFields(values)&'<button>Save content</button></form><form method="post" action="/training-tracker/admin/reset"><input type="hidden" name="scope" value="content"><button class="danger">Reset content defaults</button></form></div><div class="card"><h2>Appearance</h2><form method="post" action="/training-tracker/admin/appearance/save">';for(k in structKeyArray(theme))h&='<label>'&encodeForHtml(k)&' <input name="'&encodeForHtmlAttribute(k)&'" value="'&encodeForHtmlAttribute(theme[k])&'"></label> ';h&='<button>Save appearance</button></form><form method="post" action="/training-tracker/admin/reset"><input type="hidden" name="scope" value="appearance"><button class="danger">Reset appearance</button></form></div>';htmlOut(h&ttEnd());}
if(sub=="/admin/content/save"&&method=="POST"){ttRequireAdmin();application.training.saveContent(form);redirectTo("/training-tracker/admin##content");}
if(sub=="/admin/appearance/save"&&method=="POST"){ttRequireAdmin();application.training.saveTheme(form);redirectTo("/training-tracker/admin##appearance");}
if(sub=="/admin/reset"&&method=="POST"){ttRequireAdmin();if((form.scope?:"")=="appearance")application.training.resetTheme();else if((form.scope?:"")=="content")application.training.resetContent();redirectTo("/training-tracker/admin");}

// Compatibility aliases retained from the first Lucee conversion.
legacyWeek=reFind("^/weeks/([0-9]+)$",sub,1,true);if(legacyWeek.len[1])redirectTo("/training-tracker/week/"&ttSessionIdFrom(legacyWeek,2));
htmlOut(ttBase("Not found")&'<p>Training Tracker route not found.</p>'&ttEnd(),404);
</cfscript>
